# Generated by Django 5.2 on 2025-05-20 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_product_alter_warehouse_warehouse_type_stock_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(choices=[('ADM', 'Admin'), ('MAN', 'Manager'), ('OPE', 'Operator'), ('USR', 'User')], default='USR', max_length=10, verbose_name='user profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='warehouses',
            field=models.ManyToManyField(related_name='warehouses', to='stocks.warehouse'),
        ),
    ]
