# Generated by Django 5.2 on 2025-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('Store', 'Magasin'), ('Kanban', 'Kanban')], default='Store', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
