# Generated by Django 5.2 on 2025-05-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_warehouse_warehouse_type_alter_warehouse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True, verbose_name='internal product reference')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='product description')),
                ('product_type', models.CharField(choices=[('Consumable', 'Consumable'), ('Glass', 'Glass'), ('Chemical', 'Chemical')], null=True, verbose_name='product type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('supplier', models.CharField(max_length=30, verbose_name='supplier')),
                ('supplier_ref', models.CharField(max_length=30, verbose_name='supplier_reference')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='manufacturer')),
                ('manufacturer_ref', models.CharField(max_length=30, verbose_name='manufacturer_reference')),
                ('critical', models.BooleanField(default=False, verbose_name='is critical product ?')),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('Main store', 'Main'), ('Store', 'Store'), ('Kanban', 'Kanban')], default='Store', verbose_name='type'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_quantity', models.IntegerField(blank=True, verbose_name='stock unit quantity')),
                ('stock_unit', models.CharField(blank=True, choices=[('L', 'Liter'), ('ML', 'Milliliter'), ('G', 'Gram'), ('KG', 'Kilogram'), ('MG', 'Milligram')], verbose_name='product unit')),
                ('pack_quantity', models.IntegerField(blank=True, verbose_name='stock packaging quantity')),
                ('stock_packaging', models.CharField(blank=True, choices=[('CDB', 'Cardboard'), ('BTL', 'Bottle'), ('PCK', 'Pack'), ('BAG', 'Bag')], verbose_name='packaging')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last update date')),
                ('shelving', models.CharField(max_length=4, verbose_name='shelving')),
                ('batch', models.CharField(max_length=20, verbose_name='batch number')),
                ('expiration_date', models.DateField(null=True, verbose_name='expiration date')),
                ('reception_date', models.DateField(blank=True, verbose_name='reception date')),
                ('threshold', models.IntegerField(default=1, verbose_name='alert threshold')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stocks.product', verbose_name='product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='stocks.warehouse', verbose_name='warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='reason')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='stock')),
            ],
        ),
    ]
