# Generated by Django 5.2.1 on 2025-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_product_alter_warehouse_warehouse_type_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='location',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='building',
            field=models.CharField(default='A1', max_length=10, verbose_name='building'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='room',
            field=models.CharField(default='1000', max_length=10, verbose_name='room'),
        ),
    ]
